CREATE TABLE "HR"."NOTICE" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )
   
-- 한 줄 떨어뜨려서 써줘야함.
-- 추천 게시판(recommend)
-- re_no 숫자, title, content, writer 문자

  CREATE TABLE recommend (
  	RE_NO NUMBER(38,0),
  	TITLE VARCHAR2(100),
  	CONTENT VARCHAR2(100),
  	WRTIER VARCHAR2(100)
  
  )

  DROP TABLE RECOMMEND
  
    CREATE TABLE recommend (
  	RE_NO NUMBER(38,0),
  	TITLE VARCHAR2(100),
  	CONTENT VARCHAR2(100),
  	WRTIER VARCHAR2(100)
  
  )
  
  ALTER TABLE HR.RECOMMEND MODIFY TITLE VARCHAR2(333)

ALTER TABLE HR.RECOMMEND MODIFY CONTENT VARCHAR2(300)

ALTER TABLE HR.RECOMMEND MODIFY WRTIER VARCHAR2(300)

ALTER TABLE HR.RECOMMEND ADD VIEWCOUNT NUMBER(38,0)
